# Numpy: 
- Numpy is short for "Numerical Python" 
- NumPy is a Python library.
- NumPy is used for working with arrays.
**NumPy:**

- NumPy is a low level library written in C (and FORTRAN), for high level mathematical functions.

- NumPy cleverly overcomes the problem of running slower algorithms on Python using multidimensional arrays and functions that operates on Arrays.

- Any algorithm can then be expressed as a function on arrays, allowing the algorithm to be run quickly

- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

- At the core of the NumPy package, is the ``ndarray object``. This encapsulates n-dimensional arrays of homogeneous data types

- NumPy is the basis of Pandas, Matplotlib, Skikit Learn. They all are developed over NumPy

## Why Numpy?
- In python, we have lists that serve the purpose of arrays, but they are slow to process. 
- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
- The array object in NumPy is called ``ndarray``, it provides a lot of supporting functions that make working with ``ndarray`` very easy.

## Advantages of Numpy
- Allows several mathematical operations
- Faster operations.

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

> **Note:** Hence NumPy brings the speed of C and convenience of Python.

---

## Download Numpy

``pip install numpy``

## Import Numpy

``import numpy as np``

> **Note:** Now the NumPy package can be referred to as np instead of numpy. It is just an alias. 

## Check numpy version


In [1]:
import numpy as np
print(np.__version__)

2.3.2


## Create a NumPy Array (ndarray object)

- NumPy is used to work with arrays. The array object in NumPy is called ndarray.

- We can create a NumPy ndarray object by using the ``array()`` function.

> **Note:** To create an ndarray, we can pass any python sequence like: ``list, tuple or any array-like object`` into the ``array()`` method, and it will be converted into an ndarray:

In [2]:
#pass list
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#pass tuple
np_array = np.array((1,2,3,4,5))
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


--- 
## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays)

> **nested array:** are arrays that have arrays as their elements.

## 0-D array (Also called Scalers)

In [4]:
import numpy as np

arr0 = np.array(42)

print(arr0)

42


## 1D array (Also called Vector)
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

In [5]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


## 2D Arrays (Also called Matrix)
- An array that has 1-D arrays as its elements is called a 2-D array.

In [6]:
import numpy as np
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


## 3D arrays (Also called Tensors)
- An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [7]:
import numpy as np
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


> **Note:** By default, elements in NumPy array are ``integers (int32 or int64 depending upon system)``. But we can change it using ``.dtype`` attribute.

## ``dtype``

In [8]:
a = np.array([1,2,3], dtype=float)
print(a)

[1. 2. 3.]


In [9]:
a = np.array([1,2,3], dtype=bool)
print(a)

[ True  True  True]


In [10]:
a = np.array([1,2,3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


## ``np.arange()``
- used to generate elements between a particular range.

In [11]:
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
b = np.arange(1,11,2)
print(b)

[1 3 5 7 9]


## ``reshape()``
- change the shape of the array

In [13]:
a = np.arange(1,11)
b = a.reshape(2,5)

print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
c = np.arange(12).reshape(3,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


##  Intial Placeholders in Array

### 1. Create a numpy array of Zeros
Using ``np.zero((row,cols))`` we can create a numpy array with all values as ``0``


In [15]:
a = np.ones((2,2))
print(a)

[[1. 1.]
 [1. 1.]]


### 2. Create a numpy array of Zeros
Using ``np.ones((row,cols))`` we can create a numpy array with all values as ``1``

In [16]:
b = np.zeros((2,2))
print(b)

[[0. 0.]
 [0. 0.]]


### 3. Create a numpy array with particular value
Using ``np.full((row,cols) , value)`` we can creates array filled with specified value

In [17]:
z = np.full((3,3), 5)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


### 4. Create Identity NumPy arrays
An identity matrix is a square matrix where:
- All diagonal elements (from top-left to bottom-right) are ``1``
- All other elements are ``0``

Using ``np.eye(rows)``, we can create a identity matrix of (row x row)

Alternately, using ``np.identity(row)``, we can do the same.


In [18]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
b = np.identity(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Create a NumPy array with random values.
Using ``np.random.random((row,cols))``

In [20]:
c = np.random.random((3,4))
print(c)

[[0.43609667 0.13264863 0.42580916 0.57261453]
 [0.03959762 0.34211803 0.61390075 0.77188867]
 [0.75699752 0.18525163 0.92270804 0.96861238]]


> **Note:** By defalt, ``random.random()`` function gives floating point numbers, for integers values we have:

## Create a NumPy array with random integers (within a specific range).

Using ``np.random.randint((shape))``

In [21]:
import numpy as np
d = np.random.randint(10,100, (3,5)) # (range(dimesnions))
print(d)

[[34 30 38 54 69]
 [73 56 68 86 71]
 [53 86 45 18 69]]


## NumPy array with Evenly spaced values.

### 1. By specifying the number of values we want...
- using ``np.linspace()`` we cangenerate value which are linearly spread (or evenly spread)

- It specifies the number of value we want

In [22]:
e = np.linspace(-10,10,9)  #(range, number of elements)
print(e)

[-10.   -7.5  -5.   -2.5   0.    2.5   5.    7.5  10. ]


> From -10 to 10, and there should be exaclty 9 elements.

### 2. By specifying the step number.

- using ``np.arange()`` we can generate elements between a range with or without steps.

- It specifies the number of steps we want

In [23]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


## Convert a list/tuple to a NumPy array

In [24]:
li = [10,20,30,40,50]
print(type(li))

np_array = np.asarray(li)
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [25]:
tp = (10,20,30,40,50)
print(type(tp))

np_array = np.asarray(tp)
print(type(np_array))

<class 'tuple'>
<class 'numpy.ndarray'>


---

## NumPy array attributes.

- Every NumPy array is an Object of NumPy class
- So every NumPy array can access attributes of NumPy class.

## 1. Lets create some arrays with different dimensions

In [26]:
a1 = np.arange(10)

a2 = np.arange(12, dtype = float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

## 2. Number of dimensions - ``ndim``


In [27]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


## 3. Number of Items in each Dimensions - ``shape``

In [28]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


- **(10,) :** 10 items in an 1D array

- **(3, 4) :** a 2D array, with 3 rows and 4 cols

- **(2, 2, 2) :** a 3D array, with two 2D array, each with 2 rows and 2 cols.

## 4. Number of Items in Array - ``size``

In [29]:
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


## 5. Size occupied by each item - ``itemsize``

In [30]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


## 6. Datatype of Elements in an Array - ``dtype``

In [31]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


## 7. Changing Datatype - ``astype``

In [32]:
x = a3.astype(np.int32)
print(x.dtype)

y = a3.astype(np.int16)
print(y.dtype)

z = a3.astype(np.int8)
print(z.dtype)


int32
int16
int8


---

## **Array Operations**

In [33]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

## 1. Scaler Operations

Operation on only 1 array

## 1.1 Arithmetic

In [34]:
print(a1*2)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [35]:
print(a1+2)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [36]:
print(a1-2)

[[-2 -1  0  1]
 [ 2  3  4  5]
 [ 6  7  8  9]]


In [37]:
print(a1/2)

[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]


## 1.2 Relational

In [38]:
print(a2>20) #itemwise comparison

[[False False False False]
 [False False False False]
 [False  True  True  True]]


In [39]:
print(a2==20)

[[False False False False]
 [False False False False]
 [ True False False False]]


## 2. Vector Operation
Between 2 NumPy array

## 2.1 Arithmetic

In [40]:
print(a1+a2) #itemwise add

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


> **Note:** In python list, sum ``(+)`` operator concatenate both the list. But in NumPy array, itemwise addition will be performed

In [41]:
print(a1-a2)

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]


In [42]:
print(a1*a2)

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [43]:
print(a1/a2)

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


--- 

## **Array Functions**

## 1. Mathematical Operation using Array functions. 
Earlier we perform mathematical operations using ``(+, -, *, /)``. But we can also perform it using array functions. 

- ``np.add()``
- ``np.subtract()``
- ``np.multiply()``
- ``np.divide()``


In [44]:
print(np.add(a1,a2))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [45]:
print(np.subtract(a1,a2))

[[-12 -12 -12 -12]
 [-12 -12 -12 -12]
 [-12 -12 -12 -12]]


In [46]:
print(np.multiply(a1,a2))

[[  0  13  28  45]
 [ 64  85 108 133]
 [160 189 220 253]]


In [47]:
print(np.divide(a1,a2))

[[0.         0.07692308 0.14285714 0.2       ]
 [0.25       0.29411765 0.33333333 0.36842105]
 [0.4        0.42857143 0.45454545 0.47826087]]


## 2. ``min()``, ``max()``
- returns minimum and maximum elements of an array

In [48]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
print(np.max(a1))

11


In [50]:
print(np.min(a1))

0


## 3. ``Axis`` in Numpy

Axis can have 2 value
1. ``1``: represents rows
2. ``0``: represents columns

**Example:** We have to find row-wise ``min`` and column-wise ``max``


In [51]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [52]:
print(np.min(a1, axis=0))

[0 1 2 3]


In [53]:
print(np.max(a1, axis=1))

[ 3  7 11]


## 3. ``mean``, ``median``, ``std``, ``var``
Mean, median, standard devaition, and variance

In [54]:
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [55]:
print(np.mean(a1))

5.5


In [56]:
print(np.mean(a1, axis=1)) #row-wise mean

[1.5 5.5 9.5]


In [57]:
print(np.median(a1, axis=1))

[1.5 5.5 9.5]


In [58]:
print(np.std(a1))

3.452052529534663


In [59]:
print(np.var(a1))

11.916666666666666


## 4. Trignometric Functions

In [60]:
print(np.sin(a1)) #item-wise sin of each value

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


## 5. Dot product
``(a,b).(b,c) = (a,c)``

In [61]:
a = np.arange(12).reshape(3,4)
b = np.arange(12,24).reshape(4,3)

In [62]:
print(np.dot(a,b))   # (3,4).(4,3) = (3,3)

[[114 120 126]
 [378 400 422]
 [642 680 718]]


## 6. Log and Exponents

In [63]:
print(np.log(b))

[[2.48490665 2.56494936 2.63905733]
 [2.7080502  2.77258872 2.83321334]
 [2.89037176 2.94443898 2.99573227]
 [3.04452244 3.09104245 3.13549422]]


In [64]:
print(np.exp(b))

[[1.62754791e+05 4.42413392e+05 1.20260428e+06]
 [3.26901737e+06 8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08]
 [1.31881573e+09 3.58491285e+09 9.74480345e+09]]


## 7. ``round``, ``floor``, ``ceil``

In [65]:
a = np.random.random((2,3))*100
print(a)

[[71.08615827 86.82053023 16.65649197]
 [46.90974597 40.07848831 84.27537741]]


In [66]:
b = np.round(a)
print(b)

[[71. 87. 17.]
 [47. 40. 84.]]


In [67]:
b = np.floor(a)
print(b)

[[71. 86. 16.]
 [46. 40. 84.]]


In [68]:
b = np.ceil(a)
print(b)

[[72. 87. 17.]
 [47. 41. 85.]]


---

## Indexing and Slicing

In [69]:
a1 = np.arange(10)

a2 = np.arange(12, dtype = float).reshape(3,4)

a3 = np.arange(8).reshape(2,2,2)

### **Indexing:** One item at a time

### 1D array
- For 1D array it behave same like a list.
- Let's print 1st item of ``a1``

In [70]:
print(a1[0])

0


### 2D Array
- Let's print item at 2nd row & 3rd col


| a2[1,2]  | 1   | 2   |
|---------|--------|---|
| 2D Array | row | col |

In [71]:
print(a2[1,2])

6.0


### 3D Array
- Let's print item at 2nd matrix, 1st row, 2nd col

| a2[1,0,1]  | 1   | 0   |  1 |
|---------|---------|-----|-----|
| 3D Array | depth/matrix | row | col |

In [72]:
print(a3[1,0,1])

5


### **Slicing:** More than 1 item at a time

In [73]:
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [74]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [75]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


### 1. 1D array: From index 2 to index 4

In [76]:
a1[2:5]

array([2, 3, 4])

### 2. 2D Array: 1st row & all elements

In [77]:
print(a2[ 0 , :])

[0. 1. 2. 3.]


### 3. 2D Array: 2nd col & all elements

In [78]:
print(a2[ : , 1])

[1. 5. 9.]


### 4. 2D Array: 

| 5 | 6 |
|---|---|
| 9 | 10 |

In [79]:
print(a2[ 1: , 1:3])

[[ 5.  6.]
 [ 9. 10.]]


### 5. 2D Array:

| 0 | 3 |
|---|---|
| 8 | 11 |

In [80]:
print(a2[ ::2 , ::3 ])

[[ 0.  3.]
 [ 8. 11.]]


### 6. 2D Array:

| 1 | 3 |
|---|---|
| 9 | 11 |

In [81]:
print(a2[ ::2 , 1::2 ])

[[ 1.  3.]
 [ 9. 11.]]


### 7. 2D Array:

| 4 | 7 |
|---|---|

In [82]:
print(a2[ 1 , ::3 ])

[4. 7.]


### 8. 2D Array:

| 1 | 2 | 3 |
|---|---|---|
| 5 | 6 | 7 |


In [83]:
print(a2[ :2 , 1: ])

[[1. 2. 3.]
 [5. 6. 7.]]


### Slicing on 3D Array

In [84]:
a3 = np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### 9. 3D Array:

```txt
 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]
```

In [85]:
print(a3[ 1 , : , :])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


### 10. 3D Array:

```txt
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
```

In [86]:
print(a3[ :: 2 , : , :])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


### 11. 3D Array:

```txt
  [ 3  4  5]
```

In [87]:
print(a3[0,1,:])

[3 4 5]


### 12. 3D Array:

```txt
[10]
[13]
[16]
```

In [88]:
print(a3[1,:,1])

[10 13 16]


### 13. 3D array

```txt
[22 23]
[25 26]
```

In [89]:
print(a3[2,1:,1:])

[[22 23]
 [25 26]]


### 13. 3D array

```txt
[0 2]
[18 20]
```

In [90]:
print(a3[::2, 0, ::2])

[[ 0  2]
 [18 20]]


---

## Iterating - Using ``nditer()`` method

In [91]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [93]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [94]:
for i in a1: 
    print(i , end = " ")

0 1 2 3 4 5 6 7 8 9 

In [95]:
for i in np.nditer(a3):
    print(i, end=" ")
    

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 

> **Note:** ``nditer`` will convert our 3d array into 1d, then print each item.

## Transpose

Row <--> col

- It converts a ``(n*m)`` matrix into ``(m*n)``
- There are 2 ways to do it
    1. using ``np.transpose()`` method 
    2. Using ``T`` attribute

In [96]:
x = np.arange(10).reshape(2,5)
print(x.shape)

(2, 5)


In [97]:
y = np.transpose(x)
print(y.shape)

(5, 2)


In [98]:
y = x.T
(y.shape)

(5, 2)

> **Note:** ``np.transpose`` or ``.T`` doesn't transpose the 2D array permanently, it just provide a copy of Transposed Matrix.

---

## Stacking And Splitting


## Stacking: Append two or more Arrays
There are 2 types of Stacking

1. Horizontal Stacking: 

- ``.hstack``
- Stacks arrays side by side (along columns)
- Requires that the arrays have the same number of columns.
- ``.hstack`` takes only 1 argument, so pass all the array name in one tuple.

2. Vertical Stacking: 

- ``.vstack`` 
- Stacks arrays on top of each other (along rows).
- Requires that the arrays have the same number of rows.
- ``.vstack`` takes only 1 argument, so pass all the array name in one tuple.

> Image: Horizontal Stack

<img src = "https://www.w3resource.com/w3r_images/numpy-manipulation-hstack-function-image-1.png" width="400">

> Image: Vertical Stack

<img src = "https://www.w3resource.com/w3r_images/numpy-manipulation-vstack-function-image-1.png" width="400">


In [99]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [100]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [102]:
a4_hstack = np.hstack((a4,a5))
print(a4_hstack)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [103]:
a4_vstack = np.vstack((a4,a5))
print(a4_vstack)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


## Splitting : Opposite of Stacking, break arrays into parts
There are 2 types of Splitting

1. Horizontal Splitting: 
- ``.hsplit``
- Splits **columns** into 2 parts

2. Vertical Splitting:
- ``.vsplit``
- Splits **rows** into 2 parts

> Image: Horizontal Split

<img src = "https://www.w3resource.com/w3r_images/numpy-manipulation-array-hsplit-function-image-2.png" width="400">

> Image: Horizontal Split

<img src = "https://www.w3resource.com/w3r_images/numpy-manipulation-array-vsplit-function-image-2.png" width="400">

In [104]:
a4_hsplit = np.hsplit(a4,2) # into 2 parts
a4_hsplit

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [105]:
a4_hsplit = np.hsplit(a4,4) # into 4 parts
a4_hsplit

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [106]:
a4_vsplit = np.vsplit(a4,3) #into 3 parts
a4_vsplit

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]